# Generated by Django 6.0.1 on 2026-01-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': ('category',), 'verbose_name_plural': 'categories'},
        ),
    ]
